#!/usr/bin/env python3
import os
import gzip

def compress_data(data):
    """Compress data using gzip with maximum compression"""
    return gzip.compress(data, 9)

def generate_webfiles_header(web_interface_dir, output_file):
    """Generate webfiles.h from web_interface directory with correct variable names"""
    
    file_map = {
        'index.html': 'indexhtml',
        'scan.html': 'scanhtml',
        'ssids.html': 'ssidshtml',
        'attack.html': 'attackhtml',
        'settings.html': 'settingshtml',
        'filemanager.html': 'filemanagerhtml',
        'info.html': 'infohtml',
        'progress_bar.html': 'progressbarhtml',
        'style.css': 'stylecss',
        'js/attack.js': 'attackjs',
        'js/scan.js': 'scanjs',
        'js/settings.js': 'settingsjs',
        'js/site.js': 'sitejs',
        'js/ssids.js': 'ssidsjs',
        'lang/en.lang': 'enlang',
        'lang/in.lang': 'inlang',
        'script.js': 'script',
        'fscss.css': 'fscss',
        'repeater_proses.html': 'repeater_proses',
        'logo.png': 'logopng',
    }
    
    header = '''#ifndef webfiles_h
#define webfiles_h

// This file is auto-generated by generate_webfiles.py
// DO NOT EDIT MANUALLY

// comment that out if you want to save program memory and know how to upload the web files to the SPIFFS manually
#define USE_PROGMEM_WEB_FILES 

#ifdef USE_PROGMEM_WEB_FILES
'''
    
    total_original = 0
    total_compressed = 0
    files_processed = 0
    
    for rel_path, var_name in file_map.items():
        full_path = os.path.join(web_interface_dir, rel_path)
        if os.path.exists(full_path):
            with open(full_path, 'rb') as f:
                data = f.read()
            compressed = compress_data(data)
            hex_values = ', '.join(f'0x{b:02x}' for b in compressed)
            
            header += f'// File: {rel_path} (original: {len(data)} bytes, compressed: {len(compressed)} bytes)\n'
            header += f'const char {var_name}[] PROGMEM = {{{hex_values}}};\n\n'
            
            total_original += len(data)
            total_compressed += len(compressed)
            files_processed += 1
        else:
            print(f"Warning: File not found: {full_path}")
    
    header += f'''// Total: {files_processed} files, {total_original} bytes -> {total_compressed} bytes (gzip)
    
#endif /* USE_PROGMEM_WEB_FILES */

#endif /* webfiles_h */
'''
    
    with open(output_file, 'w') as f:
        f.write(header)
    
    print(f"Generated {output_file}")
    print(f"Total: {files_processed} files, {total_original} bytes -> {total_compressed} bytes")

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        web_interface_dir = sys.argv[1]
    else:
        web_interface_dir = 'web_interface'
    
    if len(sys.argv) > 2:
        output_file = sys.argv[2]
    else:
        output_file = 'webfiles.h'
    
    generate_webfiles_header(web_interface_dir, output_file)
